### ISSUE TITLE
Salt not bootstrapped on VM on first run(s)

### ISSUE THREAD

**Issue by vespakoen** [vmware-archive/salty-vagrant#106]
Whenever I do a "vagrant up" for the first time, bootstrapping is not happening.
This is on Mac OS X (10.8.5), Virtualbox (4.2.18), vagrant-salt (0.4.0)

After destroying the box, and "upping" it again, it works

```
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
➜  dev-machine-test git:(master) ✗ vagrant halt
[default] Attempting graceful shutdown of VM...
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
➜  dev-machine-test git:(master) ✗ vagrant halt
[default] Attempting graceful shutdown of VM...
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
➜  dev-machine-test git:(master) ✗ vagrant destroy
Are you sure you want to destroy the 'default' VM? [y/N] y
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
[default] Running cleanup tasks for 'salt' provisioner...
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
[default] Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion was not found.
Checking if salt-call is installed
salt-call was not found.
Bootstrapping Salt... (this may take a while)
```

**Comment by s0undt3ch** [comment]
Is OSX the host or the guest?

If it's the guest, the bootstrap script does not support it, yet.

If its the host, which is the guest system?

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Koen Schmeets" notifications@github.com
Para: "saltstack/salty-vagrant" salty-vagrant@noreply.github.com
Assunto: [salty-vagrant] Salt not bootstrapped on VM on first run(s) (#106)
Data: sex, Out 11, 2013 13:40
Whenever I do a "vagrant up" for the first time, bootstrapping is not happening.

This is on Mac OS X (10.8.5), Virtualbox (4.2.18), vagrant-salt (0.4.0)

After destroying the box, and "upping" it again, it works

➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
➜  dev-machine-test git:(master) ✗ vagrant halt
[default] Attempting graceful shutdown of VM...
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
➜  dev-machine-test git:(master) ✗ vagrant halt
[default] Attempting graceful shutdown of VM...
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
➜  dev-machine-test git:(master) ✗ vagrant destroy
Are you sure you want to destroy the 'default' VM? [y/N] y
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
[default] Running cleanup tasks for 'salt' provisioner...
➜  dev-machine-test git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Mounting shared folders...
[default] -- /srv
[default] -- /vagrant
[default] Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion was not found.
Checking if salt-call is installed
salt-call was not found.
Bootstrapping Salt... (this may take a while)

&mdash;

**Comment by vespakoen** [comment]
It is the host, the guest system is precise64, this also happens on precise32.

Here is my code: www.github.com/vespakoen/dev-machine
You can use the bootstrap script to run it:
https://github.com/Vespakoen/dev-machine/blob/master/bootstrap.sh

**Comment by akoumjian** [comment]
This is the known behavior of the plugin. It will not reprovision on vagrant up after halting, and is intentional. `vagrant provision` should work though.

**Comment by vespakoen** [comment]
Ah, I was not aware of that option, that works great, thanks!

It still is weird that it does not provision on the first run, but does after destroying and recreating the box.

But hey! My problem is solved so I will close this.
