### ISSUE TITLE
Explore using  vagrant-vbguest gem to update guest additions on vagrant up

### ISSUE THREAD

**Issue by benhosmer** [vmware-archive/salty-vagrant#12]
I found this while troubleshooting an earlier issue with my Virtualbox guest additions being newer than the guest additions installed on the vagrant box I was using.

[This](http://blog.carlossanchez.eu/2012/05/03/automatically-download-and-install-virtualbox-guest-additions-in-vagrant/) blog post here gives an idea of what it does.

The repo is [here](https://github.com/dotless-de/vagrant-vbguest), but I think I just installed it as a gem.

It might be an option. I used it a little, but wound up just updating the additions myself and then exporting a new box because if I remember properly, salty still had a conflict.

**Comment by akoumjian** [comment]
I don't really think this falls within the scope of salty. This is something the user can install and use in their Vagrantfile(s) independently of a salt provisioner. It is up to users to maintain their own boxes and virtualbox additions.

**Comment by benhosmer** [comment]
It was just a thought. I agree though, it adds some complexity and may not be SALTY's goal.
