### ISSUE TITLE
Wrong Debian version/codename

### ISSUE THREAD

**Issue by rnd42** [vmware-archive/salty-vagrant#17]
The Readme shows that this is compatible with Debian 6.0 however in the install script it is looking for a codename of "wheezy" or "jessie".  Wheezy is Debian 7.0 and Jessie will be Debain 8.0.

I tried using this with a Debain 6.0 "Squeeze" 32 bit image and it failed with the following error message:

```
[default] Adding salt repository.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

add-apt-repository -y ppa:saltstack/salt
```

It would seem that for some reason Debain Squeeze is being treated as if it is Ubuntu...

**Comment by rnd42** [comment]
Sorry, I guess I didn't look close enough to see the Debian 6.0 code just below the 7.0/8.0 case...

I realized that I'm not working on the newest source (using the Ubuntu/Debain install instructions I got version 0.1.2).  I tried to download and install it from sources as documented (revision hash 3167c53) but got the message:

```
$ vagrant up
There was a problem with the configuration of Vagrant. The error message(s)
are printed below:

vm:
* The provisioner 'salt' doesn't exist.
```

This is probably because the only way I could get 'vagrant gem ...' to install the package was with the flags '--no-rdoc --no-ri' due to complaints about 'lib' being missing when ever the 'ri' or 'rdoc' portion of the install got to vagrant-salt:

```
Installing ri documentation for vagrant-salt-0.1.3...
File not found: lib
ERROR:  While generating documentation for vagrant-salt-0.1.3
... MESSAGE:   exit
... RDOC args: --ri --op /home/rnd/.vagrant.d/gems/doc/vagrant-salt-0.1.3/ri lib --title vagrant-salt-0.1.3 Documentation --quiet
```

I've never really worked with Ruby so I am likely causing my own problem here...

Finally, I built the .gem from a clone of the git repo and everything worked, so I guess this issue report was completely unnecessary...  Sorry about that, not my best day!

**Comment by benhosmer** [comment]
It doesn't look like currently there is not support for squeeze:

```
elif [ $OS = 'Debian' ]; then
            if [ $CODENAME = 'wheezy' -o $CODENAME = 'jessie' ]; then
                log "Installing for Debian Weezy/Jessie."
                do_with_root apt-get -y install salt-minion
            else
                log "Debian $CODENAME is not supported."
                exit 1
            fi
        else
            log "Debian variant $OS not supported."
            exit 1
```

It looks like from the [SALT Documentation](http://docs.saltstack.org/en/latest/topics/installation/debian.html) that we'll need to add the backport support to the [bootstrap-salt-minion.sh](https://github.com/saltstack/salty-vagrant/blob/develop/scripts/bootstrap-salt-minion.sh) script.

```
cat <<EOF | sudo tee /etc/apt/sources.list.d/backports.list
deb http://backports.debian.org/debian-backports squeeze-backports main
EOF
sudo apt-get update
sudo apt-get -t squeeze-backports install salt-master
sudo apt-get -t squeeze-backports install salt-minion
```
