### ISSUE TITLE
Setup now prompting to confirm about minion config issue

### ISSUE THREAD

**Issue by howardroark** [vmware-archive/salty-vagrant#34]
Just today I compiled a gem from the HEAD revision on github and installed it to Vagrant.  I am now getting prompted to confirm this when bringing a new machine up...

[default] Setting up salt-common (0.10.1-3~bpo60+1) ...
[default] Setting up salt-minion (0.10.1-3~bpo60+1) ...
[default] Configuration file `/etc/salt/minion'
[default]  ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
[default]    What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
[default]  The default action is to keep your current version.
[default] *** minion (Y/I/N/O/D/Z) [default=N] ?
[default] Configuration file`/etc/salt/minion'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
**\* minion (Y/I/N/O/D/Z) [default=N] ?

This was not happening with the revision from last week.  The main issue here is that Vagrant doesn't really let me properly input anything to continue, so it really just fails.

I am using a debain 6 box.  I am compiling from github because an issue was fixed last week where the bootstrap script was having issues with debian version 6.0.6.  This is what is in the Vagrantfile...

  config.vm.provision :salt do |salt|
    salt.run_highstate = true

```
## Optional Settings:
salt.minion_config = "config/salt/minion.conf"
# salt.salt_install_type = "git"
# salt.salt_install_args = "develop"

## Only Use these with a masterless setup to
## load your state tree:
salt.salt_file_root_path = "config/salt/roots/salt"
salt.salt_pillar_root_path = "config/salt/roots/pillar"
```

  end

Any help is really appreciated.  For now I will just roll back the repo which I cloned to an earlier state and compile the gem from that.

Thanks!

**Comment by akoumjian** [comment]
Ah, good catch. Seems to me that we need to pass additional options to debian's apt-get command.

**Comment by howardroark** [comment]
I'm happy that made sense.  For now I will roll back to 3898fdfd8c6df0a2d8683655dc746d87bf20018b.  Ping me back here when or if you do manage to take a stab at the issue.  

I will gladly retest.

**Comment by akoumjian** [comment]
Go ahead and test this, see if it fixes the issue for you.

**Comment by howardroark** [comment]
Works great.  Thanks a lot.
