### ISSUE TITLE
Config to install salt develop still installs latest release

### ISSUE THREAD

**Issue by benhosmer** [vmware-archive/salty-vagrant#46]
I've set my Vagrantfile like this:

```
Vagrant::Config.run do |config|
  ## Chose your base box
  config.vm.box = "bensprecise64"
  config.vm.network :hostonly, "192.168.33.19"

  ## For masterless, mount your salt file root
  config.vm.share_folder "salt_file_root", "/srv", "salt/roots/salt"


  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    salt.minion_config = "salt/minion.conf"
    # salt.temp_config_dir = "/existing/folder/on/basebox/"
    salt.salt_install_type = "git"
    salt.salt_install_args = "develop"

    ## If you have a remote master setup, you can add
    ## your preseeded minion key
    # salt.minion_key = "salt/key/minion.pem"
    # salt.minion_pub = "salt/key/minion.pub"
  end
end
```

But, I still end up with:

```
vagrant@precise64:~$ salt-minion --version
salt-minion 0.10.5
vagrant@precise64:~$ salt-call --version
salt-call 0.10.5
```

**Comment by akoumjian** [comment]
Isn't that the version currently listed in git develop? What does the output look like when you run vagrant up?

https://github.com/saltstack/salt/blob/develop/salt/version.py#L8

**Comment by benhosmer** [comment]
Shouldn't it be pulling from the develop branch or am I missing something?

On Thu, Nov 29, 2012 at 4:15 PM, Alec Koumjian notifications@github.comwrote:

> Isn't that the version currently listed in git develop? What does the
> output look like when you run vagrant up?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/issues/46#issuecomment-10866756.

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by akoumjian** [comment]
Yes, it should. Can you give us the full vagrant up output and also confirm which version of salty you are using?

**Comment by benhosmer** [comment]
I'm sorry, I typed too fast. I see what you are saying now.

Vagrant up works until I get to calling state.highstate

It still never completes because of the salt-call issue in 0.10.5

On Thu, Nov 29, 2012 at 4:16 PM, Ben Hosmer ben.hosmer@gmail.com wrote:

> Shouldn't it be pulling from the develop branch or am I missing something?
> 
> On Thu, Nov 29, 2012 at 4:15 PM, Alec Koumjian notifications@github.comwrote:
> 
> > Isn't that the version currently listed in git develop? What does the
> > output look like when you run vagrant up?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/issues/46#issuecomment-10866756.
> 
> ## 
> 
> Ben Hosmer
> 
> Brevard Tech - Brevard County Florida's Tech User Group
> http://www.brevardtech.org
> 
> Drupal Developer
> http://www.radarearth.com
> 
> 321.252.9581

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by akoumjian** [comment]
Is it a bug in stable or a bug in git? If it's in a stable release, then we will want to mitigate it somehow.

**Comment by benhosmer** [comment]
I think this is a bug in stable from here: https://github.com/saltstack/salt/issues/2731

This:
    salt.salt_install_args = "0.10.4"
Works fine.

Sorry, false alarm in my haste!
