### ISSUE TITLE
salt-minion debian package seems to be missing

### ISSUE THREAD

**Issue by howardroark** [vmware-archive/salty-vagrant#47]
I am getting the below feedback when trying to spin up a new machine.  This was working up until today.  

Reading package lists...
[default] 
[default]  \* Running install_debian_60_stable()
[default] Reading package lists...
[default] 
[default] Building dependency tree...
[default] 
[default] Reading state information...
[default] 
[default] E
[default] :
[default] Unable to locate package salt-minion
[default] 
[default]  \* Failed to run install_debian_60_stable()!!!
[default]  \* Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
[default]  \* Killing logging pipe tee's with pid(s): 1451

This also happens when I follow these instructions...  http://salt.readthedocs.org/en/latest/topics/installation/debian.html

**Comment by akoumjian** [comment]
Just to confirm, it is unable to locate the package when you trying installing it manually?

If so, it sounds like there is a package missing from the backports repo and we will need to file an issue on salt.

**Comment by howardroark** [comment]
Manually fails too...

http://pastebin.com/sPgs7NDN
