### ISSUE TITLE
"daily" does not work on CentOS 6.3

### ISSUE THREAD

**Issue by alecthomas** [vmware-archive/salty-vagrant#48]
Appears to be missing a bunch of dependency packages:

```
[default] Bootstrapping salt-minion on VM...
[default]  * System Information:
[default]      CPU:          GenuineIntel
[default]      CPU Arch:     x86_64
[default]      OS Name:      Linux
[default]      OS Version:   2.6.32-279.14.1.el6.x86_64
[default]      Distribution: CentOS 6.3
[default]  * INFO: install_centos_63_daily_deps not found....
[default]  * INFO: install_centos_63_deps not found....
[default]  * INFO: install_centos_daily_deps not found....
[default]  * INFO: install_centos_deps not found....
[default]  * INFO: install_centos_63_daily not found....
[default]  * INFO: install_centos_daily not found....
[default]  * INFO: config_centos_63_daily_minion not found....
[default]  * INFO: config_centos_63_minon not found....
[default]  * INFO: config_centos_daily_minion not found....
[default]  * INFO: config_centos_minion not found....
[default]  * INFO: Found function config_minion
[default]  * INFO: install_centos_63_daily_post not found....
[default]  * INFO: install_centos_63_post not found....
[default]  * INFO: install_centos_daily_post not found....
[default]  * INFO: install_centos_post not found....
 * ERROR: No dependencies installation function found. Exiting...
 * Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap-salt-minion.sh -c /tmp/ daily 
```

**Comment by akoumjian** [comment]
There is no daily package built for CentOS. However, this shows we need to update the docs to reflect that. I will leave this open till docs are updated.

**Comment by s0undt3ch** [comment]
The only daily we have is for ubuntu, correct?

**Comment by akoumjian** [comment]
Yes

Sent from my mobile.

On Dec 12, 2012, at 4:30 PM, Pedro Algarvio notifications@github.com
wrote:

The only daily we have is for ubuntu, correct?

On 12-12-2012 19:46, Alec Koumjian wrote:

> There is no daily package built for CentOS. However, this shows we need
> to update the docs to reflect that. I will leave this open till docs are
> updated.
> 
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/saltstack/salty-vagrant/issues/48#issuecomment-11306307>.

—
Reply to this email directly or view it on
GitHubhttps://github.com/saltstack/salty-vagrant/issues/48#issuecomment-11316959.

**Comment by s0undt3ch** [comment]
I'll take care of that.

**Comment by s0undt3ch** [comment]
This can be closed. The bootstrap script now only allows daily installations for distros that actually support them.
