### ISSUE TITLE
Installing gem with vagrant gem installs vagrant-salt globally

### ISSUE THREAD

**Issue by ghost** [vmware-archive/salty-vagrant#50]
This issue is the same as #6 but I couldn't reopen it.

I'm running Arch Linux and vagrant 1.0.5, when I do:

``` sh
$ vagrant gem install vagrant-salt
# ... Installs all the things
Installing RDoc documentation for vagrant-salt-0.3.1.
```

Then, if i do

``` sh
$ gem list
# ...
vagrant-salt (0.3.1)
# but
$ vagrant gem list

** LOCAL GEMS **

# shows NOTHING!
```

I can require `vagrant-salt` form an irb console:

``` irb
irb(main):001:0> require 'vagrant-salt'
=> true
```

But when trying to start vagrant it will fail with the following message:

``` sh
$ vagrant up
There was a problem with the configuration of Vagrant. The error message(s)
are printed below:

vm:
* The provisioner 'salt' doesn't exist.
```

Looks like the gem installed via vagrant is not installed correctly?

**Comment by akoumjian** [comment]
What happens when you install another gem to the vagrant gem environment? Does it also show up in `gem list` but not `vagrant gem list`?

If so, this may be a problem with the vagrant installation. Vagrant is supposed to have an isolated rubygems installation with it.

**Comment by ghost** [comment]
I tried installing `vagrant-screenshot` and got the same problem so I guess is a Vagrant issue. I'm going to install Vagrant from source to see if the issue is fixed upstream.

Thanks for the quick response!

**Comment by ghost** [comment]
I'm closing this issue since it has been confirmed that is a problem with vagrant itself.

**Comment by akoumjian** [comment]
@alejandrogomez : Let us know if you find a solution, in case others find their way here. We can add an installation note to the docs.

**Comment by ghost** [comment]
@akoumjian sure! I filled an issue in vagrant so I hope we can find a solution.

**Comment by ghost** [comment]
The issue was caused by the `/etc/gemrc` config file in Arch Linux. It has the `--user-install` flag set so all the packages are installed local to the logged in user. This caused vagrant to install the gems for my user instead of doing it in the isolated RubyGems environment that vagrant has.

**Comment by orclev** [comment]
I just got bit by this exact issue. For now I just commented out the line in /etc/gemrc, installed salty-vagrant and then uncommented the line again. Would it be possible to add a note onto the project readme for Arch users pointing out this problem until such time as either Arch or Vagrant comes up with a fix for this problem?
