### ISSUE TITLE
Does not run on Ubuntu 12.04(host), Ubuntu 12.04(vm)

### ISSUE THREAD

**Issue by Zogg** [vmware-archive/salty-vagrant#51]
By running `vagrant up` I get this stacktrace:
http://pastebin.com/xPb0kc4R

This is my Vagrantfile:
http://pastebin.com/cZLzbrYe

**Comment by akoumjian** [comment]
For reference to others this is likely a Virtualbox / vagrant networking issue of some kind (see: mitchellh/vagrant#516 )

May I close this ticket since it is not a salty-vagrant specific issue?

**Comment by Zogg** [comment]
Yep. Thanks for assistance. ^.^
