### ISSUE TITLE
enhancement request: mailing list for salty-vagrant

### ISSUE THREAD

**Issue by msacks** [vmware-archive/salty-vagrant#52]
Hello,
I have an enhancement request to create a mailing list or google group.

**Comment by akoumjian** [comment]
Currently we just use the [salt users google group](https://groups.google.com/forum/#!forum/salt-users). Not sure if you thought we should have a separate one for salty-vagrant, but I would argue it is not yet large enough for a separate list. I'll add the mailing list to the readme.
