### ISSUE TITLE
Error on file_client: local for masterless salt (Debian 6)

### ISSUE THREAD

**Issue by guglielmo** [vmware-archive/salty-vagrant#56]
Although the configuration file specified in the Vagrantfile contains the `file_client: local` definition, whenever starting up with `vagrant up`, the configuration never overwrites the one put in `/etc/salt/minion` by the `bootstrap-salt-minion.sh` installation script.

Maybe I'me getting that wrong, but I'm not able to have a debian squeeze start correctly, without copying the configuration manually in the right place.

**Comment by roncohen** [comment]
+1

**Comment by akoumjian** [comment]
I am unable to reproduce on squeeze with current version of salty-vagrant. 

What should happen is that salty-vagrant copies the minion config over to /tmp/minion, then runs the bootstrap script with /tmp as the -c config directory. This copies the file to /etc/salt/minion. Then it installs the packages, with options to always keep existing configs over new configs.

@guglielmo Could you see if your minion config is, or ever was in /tmp? You could see if running the bootstrap script is correctly copying over the minion config by running it manually.

``` sh
sudo /tmp/bootstrap-salt-minion.sh -c /tmp
```

Lastly, it would also help to see your Vagrantfile.

**Comment by tony2nite** [comment]
I believe I'm getting the same problem on an Lucid Ubuntu 10.04.4 LTS. I'm basing my Salt setup up on https://github.com/saltstack/salty-vagrant/tree/develop/example. The minion file is copied to `/tmp` but doesn't overwrite /etc/salt/minion. `vagrant up` hangs at 'Calling state.highstate'

``` ruby
Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "base"

  ## For masterless, mount your salt file root
  config.vm.share_folder "salt_file_root", "/srv", "salt/roots/"

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    # salt.minion_config = "salt/minion.conf"
    # salt.temp_config_dir = "/existing/folder/on/basebox/"
    # salt.salt_install_type = "git"
    # salt.salt_install_args = "develop"

    ## If you have a remote master setup, you can add
    ## your preseeded minion key
    # salt.minion_key = "salt/key/minion.pem"
    # salt.minion_pub = "salt/key/minion.pub"
  end
end
```

**Comment by akoumjian** [comment]
Will revisit this later today. I have been waiting for the next stable release of the bootstrap script, where some logic needed to change.
