### ISSUE TITLE
Support Vagrant 1.1 plugin style

### ISSUE THREAD

**Issue by maspwr** [vmware-archive/salty-vagrant#59]
salty-vagrant needs support for the new Vagrant 1.1 plugin system (http://docs.vagrantup.com/v2/plugins/development-basics.html).

**Comment by lukebarton** [comment]
+1

**Comment by akoumjian** [comment]
For anyone interested, I need testers. The branch is here: https://github.com/saltstack/salty-vagrant/tree/new_format

You will want to follow the directions under "Install from Source"

**Comment by maspwr** [comment]
Things are working for me so far.  Anything in particular you want me to try out?
