### ISSUE TITLE
Installation from source instructions are broken

### ISSUE THREAD

**Issue by kamalmarhubi** [vmware-archive/salty-vagrant#62]
After untarring, the directory is not a git repository, so the steps
1. `git submodule init`
2. `git submodule update`

don't work. (Yay markdown renumbering: those are 4 and 5.)

I got it done from cloning and checking out the branch / commit of interest, but the instructions should be fixed. Ideally the tarball would include the right version, but I don't think that's a git option let alone a github option. The instructions should probably be updated to say do a git clone, as I don't see an easier way to get the bootstrap script

**Comment by akoumjian** [comment]
Thanks for fixing this.
