### ISSUE TITLE
vagrant up: The provisioner 'salt' doesn't exist

### ISSUE THREAD

**Issue by jehoshua02** [vmware-archive/salty-vagrant#65]
Environment:
- Ubuntu 12.10 Host,
- VirtualBox 4.2.10,
- Vagrant 1.0.7,
- Vagrant-Salt 0.4.0

More details: https://gist.github.com/jehoshua02/5268369

**Comment by akoumjian** [comment]
You need vagrant >=1.1 with vagrant-salt 0.4.0. Try 0.3.5 if you cannot upgrade vagrant.

**Comment by jehoshua02** [comment]
Wow, thanks for the speedy response. Do you have a compatibility matrix somewhere for the public to see???

I will try this right now and return and report.

**Comment by akoumjian** [comment]
Well, the new plugin format for vagrant just came it. It is supposed to spit out a warning message, but I guess it didn't, sorry about that. I highly recommend upgrading vagrant since 0.3.5 will be the last release for <1.1

**Comment by jehoshua02** [comment]
$ gem install vagrant -v 1.1
ERROR:  Could not find a valid gem 'vagrant' (= 1.1) in any repository
ERROR:  Possible alternatives: vagrant

**Comment by akoumjian** [comment]
You can no longer install vagrant via gems. Please see http://www.vagrantup.com/

**Comment by jehoshua02** [comment]
Installing 1.1.1 seems to do it. Strange though. I wish there would have been something along the way to prevent me from burning a whole day. Next time I'll just install every possible version combination until it works ;)

**Comment by jehoshua02** [comment]
@akoumjian Thanks a ton by the way. Your speedy responses saved me from despair.
