### ISSUE TITLE
Salt Master did not receive minion key.

### ISSUE THREAD

**Issue by theladyjaye** [vmware-archive/salty-vagrant#68]
When using with a salt-master, if vagrant reload is called and the minion key was already accepted, it attempts to wait for the key again and fails:

```
Salt successfully configured!
Waiting for minion key...
Salt Master did not receive minion key.
```

salt-key -L

```
Accepted Keys:
precise64

Unaccepted Keys:

Rejected Keys:
```

You can additionally duplicate this issue if you pass in a master config, and set `auto_accept: True` in the master config. It will wait, and the give up because the key has already been accepted.

**Comment by akoumjian** [comment]
Accept keys has been deprecated in favor of seed_master. Sorry for the inconvenience and late reply!
