### ISSUE TITLE
Bump version to v0.1.x or v0.2

### ISSUE THREAD

**Issue by kiall** [vmware-archive/salty-vagrant#7]
GitHub currently has a v0.1 tag that differs from the rubygems.org v0.1.

Probably my fault for leaving 0.1 in the gemspec though ;)

EDIT: FYI .. `rake release` should automatically build, tag and release.

**Comment by akoumjian** [comment]
rubygems is not on 0.2.0 and develop has a preliminary 0.3.0, so this should be fixed now.
