### ISSUE TITLE
Bundle Salt provisioner with Vagrant

### ISSUE THREAD

**Issue by sopel** [vmware-archive/salty-vagrant#72]
I know this has been discussed before, but given that the long awaited and significant Vagrant 1.1 upgrade triggered the Ansible provisioner to (de facto) be migrated to Vagrant core (see https://github.com/mitchellh/vagrant/pull/1465) and @mitchellh also adding a CFEngine provisioner a couple of days ago (see https://github.com/mitchellh/vagrant/commit/5fb5a60bfa2c30ae679ddb61ddc14962f21096df), this trend to bundle relevant and mature [provisioners](https://github.com/mitchellh/vagrant/tree/master/plugins/provisioners) in Vagrant core seems to call for 'Salty Vagrant' joining the parade :)
- While maintaining the provisioner within the [saltstack](https://github.com/saltstack) organization might make more sense from a development point of view, I'd argue that end users being able to provision readily configured Vagrant machines with Salt out of the box is  a more important aspect from a usability point of view, thus fostering Salt adoption.

Unfortunately I'm not in a position to help out with this myself, so I'm basically aiming to raise awareness, but since the migration to 1.1 has already been done (see #59), I'd hope this might actually be a fairly straight forward task for those in the know (if desired in the first place of course).

**Comment by akoumjian** [comment]
Hi @sopel ,

There is already a ticket for this mitchellh/vagrant#1416 and I've been hoping to do this for upwards of 6 months now. As you pointed out the new plugin format is complete. Once I had gotten that out of the way I intended to fork vagrant and merge it in directly.

Unfortunately my last two attempts to setup vagrant in a development environment have failed. As a beginner to Ruby I fear I am missing something fundamental about getting the binaries installed to my system after adding in the provisioner to the source and making the proper modifications. 

I've been to busy to give it a third attempt. I am hoping soon. If you or someone else you know wants to give it a stab, it would be appreciated.

Lastly note that unfortunately you can't just drop in a properly formatted plugin into the provisioner format. It will take some rearranging of files, etc.
