### ISSUE TITLE
Vagrant error msg

### ISSUE THREAD

**Issue by rach** [vmware-archive/salty-vagrant#76]
When I use salty vagrant (version 1.2.2)  I got an error msg.

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

salt-call state.highstate -l debug
```

It seems that `salt-call` return exit code status equal to 2 even when every works fine.

```
vagrant ssh
sudo salt-call state.highstate -l debug
echo $?
```

I'm running salt in masterless mode and I got the same error with the masterless example.
The configuration works fine but it's s a bit annoying that vagrant return this error msg.
Is there a way to silent it ?

**Comment by akoumjian** [comment]
So to clarify, salt-call is giving the wrong exit code status even when all states execute without problems? This sounds like a salt error to me. I recommend opening a ticket there. 

I would rather not tell salty-vagrant to ignore bad exit codes. What is the guest OS and what version of salt is being installed?

**Comment by binarymatt** [comment]
there is a ticket open on the salt repo for this issue: https://github.com/saltstack/salt/issues/4904

**Comment by rach** [comment]
Thanks I was not sure if it was the normal behavior of salt-call
In the case the issues has been flag already on salt.
Let's get rid of this issue.

**Comment by jdelic** [comment]
(posted a potential work-around until salt 0.16.0 comes out in #77)
