### ISSUE TITLE
Develop branch of plugin broken

### ISSUE THREAD

**Issue by raadad** [vmware-archive/salty-vagrant#78]
When calling

```
state.highstate... (this may take a while)
```

I get

```
provisioner.rb:165:in `get_pillar': undefined method `empty?' for nil:NilClass (NoMethodError) 
```

This does not occur in previous commit.

Once this is fixed ill be able to finalize the pull request into vagrant
https://github.com/mitchellh/vagrant/pull/1626

**Comment by fransvn** [comment]
This also breaks the masterless example in the repo. I was able to fix the issue by added nil check on before empty? but am not sure if this is a valid repair being unfamiliar with the project.
