### ISSUE TITLE
Debian 7 requires salt bootstrap 1.5.5

### ISSUE THREAD

**Issue by russkel** [vmware-archive/salty-vagrant#84]
The current version 1.5.4 that is submodule'd will fail on bootstrapping debian 7. This is due to salt being in the unstable packages repo and apt not being configured for that repo.

**Comment by thedrow** [comment]
Can't you just create a pull request & see what happens if you upgrade?

**Comment by russkel** [comment]
I don't follow what you mean? I can create a pull request with the submodule updated, I just didn't know if it was worth it?

As for see what happens: debian 7 successfully bootstrapped and salt is working.

**Comment by thedrow** [comment]
So create the pull request. If all tests pass correctly & the build passes it will be merged.
It's worth it. Pull Request > Issue.
