### ISSUE TITLE
Archlinux moves minion config

### ISSUE THREAD

**Issue by teburd** [vmware-archive/salty-vagrant#87]
It appears the minion config gets moved when salt is installed from /etc/salt/minion to /etc/salt/minion.pacorig

Probably best to bootstrap then place the config then start the appropriate service.

**Comment by akoumjian** [comment]
All the vagrant plugin does is copy the minion config to a temp folder, where it is picked up by the bootstrap script (https://github.com/saltstack/salt-bootstrap). Try posting an issue there.

However, this sounds more like a problem with the arch packaging, or an option during the arch package install from the bootstrap script.

**Comment by teburd** [comment]
Its not a problem with the arch packaging, its a problem with the order in which things happen.

Docs about what happens in this case with archlinux package management, https://wiki.archlinux.org/index.php/Pacnew_and_Pacsave_Files#.pacorig

The order needs to be
- Install salt package
- Copy configs to proper location
- Start salt daemons

I'll bring it up with the bootstrap script maintainer as well

**Comment by akoumjian** [comment]
How does arch handle it if you want to uninstall a package then reinstall it, but keep your custom configs? In debian systems you can install packages with options to keep the current version of a config file. @thatch45 you're an arch user, right? Surely there has to be a way to have the config there first then install the package.

The only reason I am against changing the order is that it's more convenient for most other distros to have the configs in place before installing the packages. I think @s0undt3ch would agree.

**Comment by akoumjian** [comment]
Since this is a bootstrap issue, I'm closing this issue. Conversation continued saltstack/salt-bootstrap#163

**Comment by s0undt3ch** [comment]
The current order has proven to be good for most distributions. I'll see we the order needs to change, most likely not, or, if we can specifically address Arch's differently.
