### ISSUE TITLE
Error when providing both master_key and master_pub

### ISSUE THREAD

**Issue by emilisto** [vmware-archive/salty-vagrant#94]
My vagrant config:

``` ruby
Vagrant.configure("2") do |config|

  config.vm.define :master do |v|
    v.vm.box = "raring64"

    v.vm.network :private_network, ip: "192.168.35.101"
    v.vm.synced_folder "roots/", "/srv/roots"
    v.vm.synced_folder "pillar/", "/srv/pillar"

    v.vm.provision :salt do |salt|
      salt.minion_config = "minion-configs/salt-master.minion"
      salt.run_highstate = true
      salt.install_type = 'daily'
      salt.master_key = 'keys/salt-master.pem'
      salt.master_pub = 'keys/salt-master.pub'

      salt.verbose = true
    end
  end
```

Doing a `vagrant up master` gives:

```
salt:
* You must include both public and private keys.
```

**Comment by emilisto** [comment]
I see that my Vagrantfile doesn't make any sense now — I tried to supply a `master_key` without a `master_config`. However, the error message is very strange nonetheless.

**Comment by akoumjian** [comment]
There was indeed an error in the config validation, but your vagrantfile still has a few errors. First is that you do not have install_master = true, which means even those you are copying the keys to the VM you are not installing the salt master. The second problem is that running highstate will fail unless you seed the master with the minion's public key. You can use the seed_master option for that.
