### ISSUE TITLE
Use a specific Salt environment from the Vagrantfile?

### ISSUE THREAD

**Issue by devinus** [vmware-archive/salty-vagrant#95]
I'm trying to use the same Salt roots for production and development (in development I'm using Salty Vagrant).

Is it possible to configure Salty Vagrant to use my "dev" environment? Otherwise it just uses base.

**Comment by akoumjian** [comment]
Salty Vagrant only really does a couple things:

1) installs salt on the VM
2) copies over custom minion and master configs

Everything else is just regular salt configuration. If you want the minion to use your dev environment, you need to target it in your top.sls. Try asking in #salt on IRC for more help.

**Comment by devinus** [comment]
@akoumjian Okay, it must be my own misunderstanding then.

**Comment by dkubb** [comment]
@devinus Could something like what's being discussed in #75 resolve your issue? You could use vagrant's `override.vm.provision :salt do |salt| ...` stuff to override the pillar data in your virtualbox provider block, while specifying production values in your other provider blocks. That's something I'm planning to do once #75 is released as a plugin.
